name: blog_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  get: 4.6.5
  fluttertoast: ^8.2.1
  firebase_storage: ^11.0.16
  image_picker: ^0.8.7
  uuid: ^3.0.7
  flutter_screenutil: ^5.7.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
